# Generated by Django 3.0.4 on 2021-10-01 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210930_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
    ]
